config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "plants#index"

  resources :chatrooms, only: [:index, :show, :destroy] do
    resources :messages, only: :create
  end

  get "profile", to: "pages#profile", as: :profile

  get "map", to: "plants#map"

  resources :users, only: [:index, :edit, :update]
  get 'users/:id', to: 'users#show', constraints: { id: /\d+/ }


  resources :plants do
    resources :marks, only: [:create, :edit, :update, :destroy]
    resources :matches, only: [:create, :edit, :update, :destroy]
  end

  resources :marks, only: [:index, :show, :destroy]
  resources :matches
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :user
  belongs_to :plant

  validates :user_id, uniqueness: { scope: :plant_id }
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController

  def index
    @mark = Mark.all
    @matches = Match.where(user_1_id: current_user.id).or(Match.where(user_2_id: current_user.id))

  end


  def create
    @plant = Plant.find(params[:plant_id])
    # raise
    if marked?
      render "plants/show", status: :unprocessable_entity
    else
      @mark = Mark.new

      @mark.plant = @plant # plant user marks
      @mark.user = current_user
      @user = @plant.user # user that owns the plant
      plants = current_user.plants

      if @mark.save!
        matching_mark = Mark.where(user: @user, plant_id: plants.pluck(:id)).order("created_at asc").first #array of my plants' ids
        if matching_mark.present?
          Match.create(user_1: current_user, user_2: @user, plant_1: @plant, plant_2: matching_mark.plant)
          if params[:last_action] == "index"
            redirect_to plants_path(anchor: "plant-#{@plant.id}"), notice: "💚 Your plant has a match! 💚"
            @chatroom = Chatroom.create(name: "Maple House", user_1: current_user, user_2: @user)
          else
            redirect_to plant_path(@plant), notice: "💚 Your plant has a match! 💚"
            @chatroom = Chatroom.create(name: "Banyan House", user_1: current_user, user_2: @user)
          end

        else
          if params[:last_action] == "index"
            redirect_to plants_path(anchor: "plant-#{@plant.id}")
          else
            redirect_to plant_path(@plant)
          end
        end
      end
    end
  end

  def destroy

    @mark = Mark.find(params[:id])
    @plant = @mark.plant
    @user = @mark.user
    @mark.destroy
    match = Match.where(plant_1: @plant, user_1: @user) .or(Match.where(plant_2: @plant, user_2: @user)).first
    match_destroyed = match.present?
    match&.destroy
    respond_to do |format|
      format.html do
        if match_destroyed
          redirect_to plants_path, notice: "Your Match was cancelled", status: :see_other
        else
          if request.referrer.include?(plant_path(@plant))
            redirect_to plant_path(@mark)
          else
            redirect_to plants_path
          end
        end
      end
      format.json { head :no_content }
    end
  end

  private

  def marked?
    Mark.where(user_id: current_user.id, plant_id: params[:plant_id]).exists?
  end
end

app/views/marks/_form.html.erb
<%= simple_form_for [plant, mark] do |f| %>

<%# <%= link_to "Mark", plant_marks_path(@plant), method: :post %>

  <%# <%= f.button :submit do %>
  <%= f.button :button, class: "btn-ghost buttons-card"  do %>
          <i class="fa-regular fa-heart"></i>
      <% end %>
<% end %>

app/views/marks/create.html.erb
<h1>Marks#create</h1>
<p>Find me in app/views/marks/create.html.erb</p>

app/views/marks/delete.html.erb
<h1>Marks#delete</h1>
<p>Find me in app/views/marks/delete.html.erb</p>

app/views/marks/edit.html.erb
<h1>Marks#edit</h1>
<p>Find me in app/views/marks/edit.html.erb</p>

app/views/marks/index.html.erb
<div class="marks overflow-scroll">

  <%# <div class="buttons btn-back-to-plants">
    <%= link_to "<< Back to plants", plants_path, class: "btn btn-ghost" %>
  <%# </div> %>

  <div class="mm-title">
    <h1>Marks & Matches</h1>
  </div>


  <div class="mm-container">
    <div class="matches-container">
      <div class="m-title" id="your-matches">
        <h1>Your Matches</h1>
      </div>
      <div class="matches-disp">
        <% if @matches.first.nil? %>
          <p>Sorry, you have no matches...yet!</p>
        <% else %>
          <% @matches.uniq.each do |match| %>
            <div class="d-flex">
              <div class="plant-mark-1" style="background-image: url('<%= cl_image_path match.plant_1.photo.key, height: 200, width: 150, crop: :fill %>')">
                <%# <h5><strong><%= match.plant_1.name %>
                <h1><i class="fa-solid fa-infinity fa-2x"></i></h1>
              </div>
              <div class="plant-mark-2" style="background-image: url('<%= cl_image_path match.plant_2.photo.key, height: 200, width: 150, crop: :fill %>')">
                <%# <h5><strong><%= match.plant_2.name %>
                <%# <i class="fa-solid fa-infinity fa-2x"></i> %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="marks-container">
      <div class="m-title" id="your-marks">
        <h1>Your Marks</h1>
      </div>
      <div class="carousel-marks">
      <% if current_user.marks.first.nil? %>
          <p>You haven't marked any plant yet.
            <span>
              <%= link_to "Check these cuties out!", plants_path, style: "color: goldenrod" %>
            </span>
          </p>
        <% else %>
        <div id="carouselMarks" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% current_user.marks.each_with_index do |mark, index| %>
              <% if index == 0 %>
                <div class="carousel-item active">
                  <%= link_to plant_path(mark.plant) do %>
                    <%= cl_image_tag mark.plant.photo.key, height: 200, width: 150, crop: :fill %>
                  <% end %>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselMarks" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="false"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselMarks" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="false"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                </div>
              <% else %>
                <div class="carousel-item">
                  <%= link_to plant_path(mark.plant) do %>
                    <%= cl_image_tag mark.plant.photo.key, height: 200, width: 150, crop: :fill %>
                  <% end %>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselMarks" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselMarks" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
      </div>
    </div>

  </div>
</div>

app/views/marks/update.html.erb
<h1>Marks#update</h1>
<p>Find me in app/views/marks/update.html.erb</p>