config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "plants#index"

  resources :chatrooms, only: [:index, :show, :destroy] do
    resources :messages, only: :create
  end

  get "profile", to: "pages#profile", as: :profile

  get "map", to: "plants#map"

  resources :users, only: [:index, :edit, :update]
  get 'users/:id', to: 'users#show', constraints: { id: /\d+/ }


  resources :plants do
    resources :marks, only: [:create, :edit, :update, :destroy]
    resources :matches, only: [:create, :edit, :update, :destroy]
  end

  resources :marks, only: [:index, :show, :destroy]
  resources :matches
end

app/views/layouts/shared/_card_index.html.erb
<div class="card-content">
  <%# style="background-image: url('<%= cl_image_path plant.photo.key, height: 240, width: 180, crop: :fill %>
  <div class="grid-image">
    <%= link_to plant_path(plant) do %>
    <%= cl_image_tag plant.photo.key, height: 240, width: 180, crop: :fill, class:"img-card" %>
  <% end %>
  </div>

  <div class="button-swipe"><i class="fa-solid fa-bars fa-xl icon-auto-color"></i></div>
  <div class="mycard" id="plant-<%= plant.id %>">
    <%# inline if  statement to hide mark for the user %>
    <div class="buttons-card">
      <div class="card-name">
        <h2><%=link_to plant.name, plant_path(plant)%></h2>
      </div>
      <% if !current_user.plants.include?(plant) %>
        <% if mark.present? %>
          <%= link_to mark_path(mark), data: {turbo_method: :delete } do %>
            <i class="fa-solid fa-lg fa-heart btn"></i>
          <% end %>
        <% else %>
          <%= simple_form_for [plant, Mark.new], html: { class: "d-inline-block" } do |f| %>
            <%= hidden_field_tag "last_action", action_name %>
            <%= f.button :button do %>
              <i class="fa-regular fa-lg fa-heart"></i>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

      <%= link_to map_path do %>
        <i class="fa-regular fa-lg fa-compass"></i>
      <% end %>
      <%# <i class="fa-regular fa-circle-user"></i> %>
      <%= link_to user_path(plant.user) do %>
      <%= cl_image_tag plant.user.photo.key, class: "card-trip-user avatar-bordered", width: 30, height: 30, crop: :fill %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/shared/_card_swiper.html.erb
<div class="swiper-slide">
      <%= link_to plant_path(plant) do %>
        <%= cl_image_tag plant.photo.key, height: 400, width: 300, crop: :fill, class: "swiper-image" %>
      <% end %>
      <div class="swiper-pagination swiper-custom-pagination"></div>
      <div class="button-grid"><i class="fa fa-th-large fa-xl icon-auto-color"></i></div>

  <div class="my-swipe-card" id="plant-<%= plant.id %>">
    <div class="swiper-buttons-card">
      <div class="swipe-card-name">
        <h2><%=link_to plant.name, plant_path(plant)%></h2>
      </div>
    <% if !current_user.plants.include?(plant) %>
      <% mark = current_user.marks.find_by(plant: plant) %>
      <% if mark.present? %>
        <%= link_to plant_mark_path(plant, mark), data: { turbo_method: :delete } do %>
          <i class="fa-solid fa-2x fa-heart btn"></i>
        <% end %>
      <% else %>
        <%= simple_form_for [plant, Mark.new], html: { class: "d-inline-block" } do |f| %>
          <%= hidden_field_tag "last_action", action_name %>
          <%= f.button :button do %>
            <i class="fa-regular fa-2x fa-heart"></i>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

      <%= link_to map_path(plant, lat: plant.latitude, lng: plant.longitude) do %>
        <i class="fa-regular fa-2x fa-compass"></i>
      <% end %>
      <%# <i class="fa-regular fa-circle-user"></i> %>
      <%= link_to user_path(plant.user) do %>

        <%= cl_image_tag plant.user.photo.key, class: "card-trip-user avatar-bordered-sw", width: 33, height: 33, crop: :fill %>

      <% end %>

    </div>
  </div>
</div>

app/views/layouts/shared/_flashes.html.erb
<%# <% if notice %>
  <%# <div class="notice alert alert-info alert-dismissible fade show m-1" role="alert"> %>
    <%# <%= notice %>
    <%# <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> %>
    <%# </button> %>
  <%# </div> %>
<%# <% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    <h2>Nothing</h2>
    </button>
  </div>
<% end %>

app/views/layouts/shared/_info_window.html.erb
<%= link_to plant_path(plant) do %>
    <%= cl_image_tag plant.photo.key, height: 80, width: 60, crop: :fill %>
<% end %>
<%= link_to user_path(plant.user) do %>
    <%= cl_image_tag plant.user.photo.key, width: 60, height: 60, crop: :fill %>
<% end %>
<%# <h5><%= link_to <img class="avatar-bordered" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" />, user_path(current_user) do %>
<%# <img class="avatar-bordered" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" /></h5> %>


<h5><%= plant.name %></h5>
<%# <h5><%= link_to user_path(current_user) do %>

<h6><%= plant.address %></h6>
<h6> <%= ["I have more plants. Check my collection!", "This plant lives in Kreuzberg, but wants to move", "Oh my god, what a cutie!", "Would you like to have this beautiful plant?", "My plant needs some love 💞", "More plants!", "Let's swap plants!", "My plant needs a date.", "Las Plantitas son vida y alegria", "Bitte tragen Sie eine Maske, wenn Sie Pflanzen tauschen möchten.", "Isn't this the most beautiful plant ever?", "This plant can be yours"].sample %> </h6>

app/views/layouts/shared/_navbar.html.erb
<div class="navbar navbar-sprouts navbar-expand-sm navbar-default navbar-lewagon">
  <div class="container-fluid" style="width: 100vw; display: flex; justify-content: center;">
      <ul style="display:flex;list-style: none">
        <% if user_signed_in? %>
          <li class="nav-item active" inlstyle="margin:5px 0px 0px;">
            <%= link_to plants_path, class: "navbar-brand" do %>
              <%# <%= image_tag "home.png" %>
              <i class="fa-solid fa-house fa-lg"></i>
            <% end %>
          </li>

          <li class="nav-item active" inlstyle="margin:5px 0px;">
            <%= link_to chatrooms_path, class: "navbar-brand" do %>
              <i class="fa-solid fa-comments fa-lg"></i>
            <% end %>
          </li>

          <li class="nav-item active" inlstyle="margin:5px 0px;">
            <%= link_to new_plant_path, class: "navbar-brand" do %>
              <%# <%= image_tag "post.png" %>
              <i class="fa-solid fa-seedling fa-lg"></i>
            <% end %>
          </li>

          <li class="nav-item active" inlstyle="margin:5px 0px;">
            <%= link_to marks_path, class: "navbar-brand" do %>
              <%# <%= image_tag "mark.png" %>
              <i class="fa-solid fa-heart fa-lg"></i>
            <% end %>
          </li>

          <li class="nav-item active" inlstyle="margin:5px 0px;">
            <%= link_to user_path(current_user), class: "navbar-brand" do %>
              <%# <%= image_tag "profile.png" %>
              <i class="fa-solid fa-user fa-lg"></i>
            <% end %>
          </li>

        <% else %>
          <% unless current_page?(new_user_registration_path) %>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
          <% if current_page?(new_user_registration_path) %>
            <li class="nav-item" style="margin-left: 10px;">
              <%= link_to "Back to Login", new_user_session_path, class: "nav-link", style: "padding-bottom: 18px; height: 10px;"%>
            </li>
          <% end %>
        <% end %>
      </ul>

  </div>
</div>

app/views/layouts/shared/_search-form.html.erb
<div class="search-form">
  <%= form_with url: plants_path, method: :get, class: "search-form-inner" do %>
    <div class="container row justify-content-center">
      <div class="d-flex col-12 py-3">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control search-input",
          placeholder: "We grow together!"
        %>
        <button class="btn-sprouts">
          <i class="fa-solid fa-leaf fa-1.5x"></i>
        </button>
      </div>
    </div>
  <% end %>
  <div class="btn-map">
    <a href="/map">
      <i class="far fa-map fa-2x"></i>
    </a>
  </div>
</div>


<div class="query-result">
  <% if params[:query] %>
      <h4 class="text-center"><%= "Did you find your new plant?" %></h4>
  <% end %>
</div>