config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "plants#index"

  resources :chatrooms, only: [:index, :show, :destroy] do
    resources :messages, only: :create
  end

  get "profile", to: "pages#profile", as: :profile

  get "map", to: "plants#map"

  resources :users, only: [:index, :edit, :update]
  get 'users/:id', to: 'users#show', constraints: { id: /\d+/ }


  resources :plants do
    resources :marks, only: [:create, :edit, :update, :destroy]
    resources :matches, only: [:create, :edit, :update, :destroy]
  end

  resources :marks, only: [:index, :show, :destroy]
  resources :matches
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :plants
  has_many :messages
  has_many :reviews

  has_many :chatrooms_as_user_1, class_name: "Chatroom", foreign_key: :user_1_id, dependent: :destroy
  has_many :chatrooms_as_user_2, class_name: "Chatroom", foreign_key: :user_2_id, dependent: :destroy

  has_many :marks
  has_many :matches

  has_one_attached :photo

  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Profile updated successfully'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:title, :body, :photo, :description)
  end

  def chatrooms
  end
end

app/views/users/chatrooms.html.erb
<ol>
<% current_user.chatrooms_as_user_1.each do |chatroom| %>
  <li>
  <br><%= chatroom.name %>
  <br><%= chatroom.user_1.email %>
  <br><%= chatroom.user_2.email %>
  </li>
  <% end %>

<% current_user.chatrooms_as_user_2.each do |chatroom| %>
  <li>
  <br><%= chatroom.name %>
  <br><%= chatroom.user_1.email %>
  <br><%= chatroom.user_2.email %>
  </li>
  <% end %>
</ol>

app/views/users/edit.html.erb
<%= form_for @user, html: { multipart: true, class: "card-trip" } do |f| %>
  <img src="https://images.unsplash.com/photo-1551970634-747846a548cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80", class="banner-img" />
  <div class="card-trip-infos">
    <div class="card-trip-user"
      <% if @user.photo.present? %>
        style="background-image: url('<%= cl_image_path @user.photo.key, width: 100, height: 100, crop: :fill %>')">
      <% end %>
      <div class="form-group avatar-edit">
        <label class="btn-sunny" for="user_photo">Change</label>
        <%= f.file_field :photo, id: "user_photo", class: "d-none" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.text_field :username, class: "form-control-username" %>
    </div>

    <div class="about-me-edit">
      <h3>About Me</h3>

      <div class="form-group">
        <%= f.text_area :description, class: "form-control-description" %>
      </div>

    </div>

      <%= f.submit "Update Profile", class: "btn btn-success" %>
      <% end %>
  <div class="nav-buttons" id="add-plant-button">
    <%= link_to "🪴 Add another Plant of Yours 🪴", new_plant_path%>
  </div>
</div>

app/views/users/edit_avatar.html.erb
<div class="modal" id="avatarModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <turbo-frame id="avatar_form">
          <%= form_for @user, url: update_avatar_user_path(@user), data: { turbo_frame: 'avatar_form' }, method: :patch do |f| %>
            <%= f.file_field :photo %>
            <%= f.submit "Change Avatar" %>
          <% end %>
        </turbo-frame>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="card-trip">
  <div class="profile">
    <img src="https://images.unsplash.com/photo-1551970634-747846a548cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" />
    <div class="card-trip-infos">
      <div class="card-trip-user"
        <% if @user.photo.present? %>
          style="background-image: url('<%= cl_image_path @user.photo.key, width: 100, height: 100, crop: :fill %>')">
        <% end %>
      </div>
      <div class=list-inline>
          <h2 id="username"><strong><%= @user.username %></strong></h2>
          <% if current_user == @user %>
            <%= link_to edit_user_path(@user) do %>
              <i class="fa-solid fa-pencil"></i>
            <% end %>
          <% end %>
      </div>
      <div class="about-me">
        <h3>About Me</h3>
        <p><%= @user.description %></p>
        <h3>My Plants</h3>
      </div>

      <div class="my-collection">
        <div class="user-plants-collection">
          <div class="grid-gallery">
            <% @user.plants.each_with_index do |plant, index| %>
              <div class="grid-item">
                <div class="thumbnail-border">
                  <%= link_to plant_path(plant) do %>
                    <%= cl_image_tag plant.photo.key, height: 100, width: 100, crop: :fill, class: "thumbnail-img" %>
                  <% end %>
                  <%= button_to plant_path(plant), method: :delete, data: { 'confirm': 'Are you sure you want to delete this plant?' }, class: 'delete-btn', remote: true do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="sign-out">
    <% if user_signed_in? %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, form: { "data-turbo-action": "replace", "data-turbo-frame": "_top" }, class: "sign-out-button" %>

    <% end %>
  </div>
</div>