config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "plants#index"

  resources :chatrooms, only: [:index, :show, :destroy] do
    resources :messages, only: :create
  end

  get "profile", to: "pages#profile", as: :profile

  get "map", to: "plants#map"

  resources :users, only: [:index, :edit, :update]
  get 'users/:id', to: 'users#show', constraints: { id: /\d+/ }


  resources :plants do
    resources :marks, only: [:create, :edit, :update, :destroy]
    resources :matches, only: [:create, :edit, :update, :destroy]
  end

  resources :marks, only: [:index, :show, :destroy]
  resources :matches
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid" style="width: 100vw;display: flex;justify-content: center;">
    <%# <%= link_to root_path, class: "navbar-brand" do %>
      <%# <%= image_tag "sprouts_logo.jpg" %>
    <%# <% end %>
    <div class="">
      <ul style="display:flex;list-style: none">
        <% if user_signed_in? %>
          <li class="nav-item active" style="margin:5px;">
            <%= link_to plants_path, class: "navbar-brand" do %>
              <%= image_tag "home.png" %>
            <% end %>
          </li>
          <li class="nav-item active" style="margin:5px;">
            <%= link_to chatroom_path(current_user), class: "navbar-brand" do %>
              <%= image_tag "chat.png" %>
            <% end %>
          </li>
          <li class="nav-item active" style="margin:5px;">
            <%= link_to new_plant_path, class: "navbar-brand" do %>
              <%= image_tag "post.png" %>
            <% end %>
          </li>
          <li class="nav-item active" style="margin:5px;">
            <%= link_to marks_path, class: "navbar-brand" do %>
              <%= image_tag "mark.png" %>
            <% end %>
          </li>
          <li class="nav-item active" style="margin:5px;">
            <%= link_to user_path(current_user), class: "navbar-brand" do %>
              <%= image_tag "profile.png" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search-form.html.erb
<br>
<div class="container row justify-content-center">
<%= form_with url: plants_path, method: :get, class: "d-flex col-sm-8 py-3" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Let's grow together!"
  %>
  <%= submit_tag "🌿", class: "btn btn-primary fa-solid" %>
<% end %>
<% if params[:query] %>
    <h2 class="text-center"><%= "Mark the plants you would like to grow at home" %></h2>
<% end %>

</div>